/**
 * Compiles assets/icons/*.svg into lib/icons.generated.ts.
 *
 * The design system's original Icon component fetched each SVG at runtime. That
 * cannot work in a server component and flashes on first paint, so the glyphs are
 * inlined at build time instead. The rules are unchanged: Lucide outlines, 24px
 * source grid, 1.75 stroke, currentColor — the stroke and colour are applied by
 * the component, so only the inner markup is stored here.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';

const SRC = path.join(process.cwd(), 'assets', 'icons');
const OUT = path.join(process.cwd(), 'lib', 'icons.generated.ts');

const files = readdirSync(SRC).filter((f) => f.endsWith('.svg')).sort();

const entries = files.map((file) => {
  const name = file.replace(/\.svg$/, '');
  const raw = readFileSync(path.join(SRC, file), 'utf8');
  const inner = raw
    .replace(/<\?xml[\s\S]*?\?>/g, '')
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/\s*\n\s*/g, '')
    .trim();
  if (!inner) throw new Error(`Empty glyph: ${file}`);
  return [name, inner] as const;
});

const body = `// Generated by scripts/build-icons.ts — do not edit by hand.
// Source: assets/icons/*.svg (Lucide, ISC). Run \`npm run icons\` after adding a glyph.

export const ICONS = {
${entries.map(([name, inner]) => `  ${JSON.stringify(name)}: ${JSON.stringify(inner)},`).join('\n')}
} as const;

export type IconName = keyof typeof ICONS;
`;

mkdirSync(path.dirname(OUT), { recursive: true });
writeFileSync(OUT, body);
console.log(`Wrote ${entries.length} glyphs to lib/icons.generated.ts`);
